Conference/Controllers/EditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Areas.Admin.Models;
using Conference.Domain.Entities;
using Conference.Models;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Omu.ValueInjecter;

namespace Conference.Controllers
{
    public class EditionController : Controller
    {

        private IEditionsService edition;
        public EditionController(IEditionsService edition) 
        {
            this.edition = edition;
        }
        // GET: Edition
        public ActionResult Index()
        {
            var getEditions = edition.GetEditions();
            return View(getEditions);
        }

        // GET: Edition/Details/5
        public ActionResult Details(int id)
        {
            var getEditionById = edition.GetById(id);
            EditionsViewModel model = new EditionsViewModel();
            model.InjectFrom(getEditionById);
            return View(model);
        }
        /*
        // GET: Edition/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Edition/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EditionsViewModel model)
        {
            if (ModelState.IsValid)
            {

                Editions newEdition = new Editions();
                newEdition.InjectFrom(model);

                var createEdition = edition.CreateEdition(newEdition);
                if (createEdition == null)
                {
                    ModelState.AddModelError("CompanyName", "Must be unique");
                    return View(model);
                }
            }
            return RedirectToAction(nameof(Index));          
        }

        // GET: Editions/Edit/5
        public ActionResult Edit(int id)
        {
            var edit = edition.GetById(id);
            EditionsViewModel model = new EditionsViewModel();
            model.InjectFrom(edit);

            return View(model);
        }


        // POST: Editions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EditionsViewModel model)
        {
            Editions edit = new Editions();
            edit.InjectFrom(model);
            var createNewEdition = edition.Update(edit);
            return RedirectToAction(nameof(Index));
        }

        // GET: Editions/Delete/5
        public ActionResult Delete(int id)
        {
            var delete = edition.GetById(id);

            EditionsViewModel model = new EditionsViewModel();

            model.InjectFrom(delete);

            return View(model);
        }

        // POST: Editions/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, EditionsViewModel model)
        {

            Editions deleteEdition = new Editions();

            deleteEdition = edition.GetById(id);

            model.InjectFrom(deleteEdition);

            edition.DeleteEdition(deleteEdition);

            return RedirectToAction(nameof(Index));

        }
        */
    }
}

Conference/Controllers/SpeakerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Areas.Admin.Models;
using Conference.Domain.Entities;
using Conference.Models;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Omu.ValueInjecter;

namespace Conference.Controllers
{
    public class SpeakerController : Controller
    {

        private ISpeakerService speaker;
        public SpeakerController(ISpeakerService speaker)
        {
            this.speaker = speaker;
        }
        // GET: Speaker
        public ActionResult Index()
        {
            var getSpeakers = speaker.GetSpeakers();
            return View(getSpeakers);
        }

        // GET: Speakers/Details/5
        public ActionResult Details(int id)
        {
            var getSpeakerById = speaker.GetById(id);
            SpeakersViewModel model = new SpeakersViewModel();
            model.InjectFrom(getSpeakerById);
            return View(model);
        }
        /*
        // GET: Speakers/Create
        public ActionResult Create()
        {
            SpeakersViewModel model = new SpeakersViewModel();
            return View(model);
        }

        // POST: Speakers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SpeakersViewModel model)
        {
            {
                if (ModelState.IsValid)
                {
                    Speakers speakersToAdd = new Speakers();
                    speakersToAdd.InjectFrom(model);

                    var addedSpeakers = speaker.CreateSpeaker(speakersToAdd);
                    if (addedSpeakers == null)
                    {
                        ModelState.AddModelError("Description", "Desciption must be unique");
                        return View(model);
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(model);

            }
        }
        // GET: Speakers/Edit/5
        public ActionResult Edit(int id)
        {
            var edit = speaker.GetById(id);
            SpeakersViewModel model = new SpeakersViewModel();
            model.InjectFrom(edit);

            return View(model);
        }

        // POST: Speakers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SpeakersViewModel model)
        {
            Speakers edit = new Speakers();
            edit.InjectFrom(model);
            var createNewSpeaker = speaker.Update(edit);
            return RedirectToAction(nameof(Index));
        }

        // GET: Speakers/Delete/5
        public ActionResult Delete(int id)
        {
            var delete = speaker.GetById(id);

            SpeakersViewModel model = new SpeakersViewModel();

            model.InjectFrom(delete);

            return View(model);
        }

        // POST: Speakers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, SpeakersViewModel model)
        {
            Speakers deleteSpeaker = new Speakers();
            deleteSpeaker = speaker.GetById(id);
            model.InjectFrom(deleteSpeaker);
            speaker.DeleteSpeakers(deleteSpeaker);
            return RedirectToAction(nameof(Index));
        }
        */
    }
}

Conference/Controllers/SponsorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Areas.Admin.Models;
using Conference.Domain.Entities;
using Conference.Models;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Omu.ValueInjecter;

namespace Conference.Controllers
{
    public class SponsorController : Controller
    {

        private ISponsorsService sponsor;
        public SponsorController(ISponsorsService sponsor)
        {
            this.sponsor = sponsor;
        }
        // GET: Sponsor
        public ActionResult Index()
        {
            var getSponsors = sponsor.GetSponsors();
            return View(getSponsors);
        }

        // GET: Sponsor/Details/5
        public ActionResult Details(int id)
        {
            var getSponsorById = sponsor.GetById(id);
            SponsorsViewModel model = new SponsorsViewModel();
            model.InjectFrom(getSponsorById);
            return View(model);
        }

        // GET: Sponsor/Create
        public ActionResult Create()
        {
            SponsorsViewModel model = new SponsorsViewModel();
            return View(model);
        }
        /*
        // POST: Sponsor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SponsorsViewModel model)
        {
            if (ModelState.IsValid)
            {

                Sponsors newSponsor = new Sponsors();
                newSponsor.InjectFrom(model);

                var createSponsor = sponsor.CreateSponsor(newSponsor);
                if (createSponsor == null)
                {
                    ModelState.AddModelError("CompanyName", "Must be unique");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Sponsors/Edit/5
        public ActionResult Edit(int id)
        {
            var edit = sponsor.GetById(id);
            SponsorsViewModel model = new SponsorsViewModel();
            model.InjectFrom(edit);

            return View(model);
        }


        // POST: Sponsors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SponsorsViewModel model)
        {
            Sponsors edit = new Sponsors();
            edit.InjectFrom(model);
            var createNewSponsor = sponsor.Update(edit);
            return RedirectToAction(nameof(Index));
        }

        // GET: Sponsors/Delete/5
        public ActionResult Delete(int id)
        {
            var delete = sponsor.GetById(id);

            SponsorsViewModel model = new SponsorsViewModel();

            model.InjectFrom(delete);

            return View(model);
        }

        // POST: Sponsors/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, SponsorsViewModel model)
        {

            Sponsors deleteSponsor = new Sponsors();

            deleteSponsor = sponsor.GetById(id);

            model.InjectFrom(deleteSponsor);

            sponsor.DeleteSponsor(deleteSponsor);

            return RedirectToAction(nameof(Index));

        }
        */
    }
}

Conference/Controllers/TalkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Areas.Admin.Models;
using Conference.Domain.Entities;
using Conference.Models;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Omu.ValueInjecter;

namespace Conference.Controllers
{
    public class TalkController : Controller
    {

        private ITalksService talk;
        public TalkController(ITalksService talk)
        {
            this.talk = talk;
        }
        // GET: Talk
        public ActionResult Index()
        {
            var getTalks = talk.GetTalks();
            return View(getTalks);
        }

        // GET: Talk/Details/5
        public ActionResult Details(int id)
        {
            var getTalkById = talk.GetById(id);
            TalksViewModel model = new TalksViewModel();
            model.InjectFrom(getTalkById);
            return View(model);
        }

        // GET: Talk/Create
        public ActionResult Create()
        {
            return View();
        }
        /*
        // POST: Talk/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TalksViewModel model)
        {
            {
                if (ModelState.IsValid)
                {

                    Talks talksToAdd = new Talks();
                    talksToAdd.InjectFrom(model);

                    var addedTalks = talk.CreateTalk(talksToAdd);
                    if (addedTalks == null)
                    {
                        ModelState.AddModelError("CompanyName", "Must be unique");
                        return View(model);
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
        }

        // GET: Talks/Edit/5
        public ActionResult Edit(int id)
        {
            var edit = talk.GetById(id);
            TalksViewModel model = new TalksViewModel();
            model.InjectFrom(edit);

            return View(model);
        }


        // POST: Talks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TalksViewModel model)
        {
            Talks edit = new Talks();
            edit.InjectFrom(model);
            var createNewTalk = talk.Update(edit);
            return RedirectToAction(nameof(Index));
        }

        // GET: Talks/Delete/5
        public ActionResult Delete(int id)
        {
            var delete = talk.GetById(id);

            TalksViewModel model = new TalksViewModel();

            model.InjectFrom(delete);

            return View(model);
        }

        // POST: Talks/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, TalksViewModel model)
        {

            Talks deleteTalk = new Talks();

            deleteTalk = talk.GetById(id);

            model.InjectFrom(deleteTalk);

            talk.DeleteTalk(deleteTalk);

            return RedirectToAction(nameof(Index));

        }
        */
    }
}

Conference/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Conference</title>

    <link rel="stylesheet" type="text/css" href="~/css/Index.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles/Index.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <header>
       @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Conference</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@

        <nav class="navbar navbar-expand-lg navbar-dark navbar-default bg-mv">
            <div class="container">
                <a class="navbar-brand active" href="/">
                    <img class="img-responsive" src="~/Image/dotnetdays.jpg" alt="dotnetdays.ro" style="width:15.6rem; background-color: #442359;" />
                </a>

                <a class="navbar-brand" asp-area="" asp-controller="Edition" asp-action="Index">Edition</a>
                <a class="navbar-brand" asp-area="" asp-controller="Speaker" asp-action="Index">Speaker</a>
                <a class="navbar-brand" asp-area="" asp-controller="Sponsor" asp-action="Index">Sponsor</a>
                <a class="navbar-brand"asp-area="" asp-controller="SponsorType" asp-action="Index">SponsorType</a>
                <a class="navbar-brand" asp-area="" asp-controller="Talk" asp-action="Index">Talk</a>
                <a class="navbar-brand" asp-area="" asp-controller="Workshop" asp-action="Index">Workshop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="menu-socials">
                        <li class="nav-item">
                            <a href="https://www.facebook.com/dotnetdays.ro" target="_blank">
                                <img src="~/image/facebook.png" alt="facebook" width="30" />
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://twitter.com/dotnetdaysro" target="_blank">
                                <img src="~/Image/twitter.png" alt="twitter" width="30" />
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://meetup.com/NET-User-Group-Iasi/" target="_blank">
                                <img src="~/image/meetup.png" alt="meetup" width="30" />
                            </a>
                        </li>
                    </ul>


                    <ul class="navbar-nav flex-grow-1" id="main-menu">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>

   <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Conference - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>